spring.application.name=moodmix
spring.datasource.url=jdbc:postgresql://localhost:5432/moodmix
spring.datasource.username=ataner
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=dev
spring.security.user.password=atag
spring.security.user.roles=USER

# Max size for files
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB



essentia.api.url=http://localhost:5000/analyze


# CORS (adjust port to your React dev server)
# spring.mvc.cors.allowed-origins=http://localhost:5173,http://localhost:3000